apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blue-green
  namespace: blue-green
spec:
  hosts:
  - "*"
  gateways:
  -  blue-green-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri: 
        prefix: /
    route:
    - destination:
        host: /
        port:
          number: 6789